#!/bin/bash

echo '/*
 * Copyright (C) 2020 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Auto-generated by topics.sh. Dont need modify this file */
'

if [[ $1 = "-c" ]]
then

echo '#include <uORB/uORB.h>
'

grep -rh ORB_DECLARE include --include=*.h

echo -n '
#undef ORB_DECLARE
#define ORB_DECLARE(x) ORB_ID(x)

const struct orb_metadata* const g_uorb_topics_list[] = {
NULL,
'
grep -rh ORB_DECLARE include --include=*.h | sed 's/;/,/g' | sort
echo -n '};
'

echo "
int g_uorb_topics_count = sizeof(g_uorb_topics_list) / sizeof(g_uorb_topics_list[0]);"

elif [[ $1 = "-h" ]]
then

echo "#ifndef __TOPICS_SRC_UORB_TOPICS_H
#define __TOPICS_SRC_UORB_TOPICS_H

#ifdef __cplusplus
extern \"C\" {
#endif
"

echo '#undef ORB_DECLARE
#define ORB_DECLARE(x) x

enum ORB_ID {
ORB_DECLARE(invalid),'

grep -rh ORB_DECLARE include --include=*.h | sed 's/;/,/g' | sort

echo -n '};

#ifdef __cplusplus
}
#endif

#endif
'
fi
